version: '2'
services:
  postgres:
    image: postgres:9.5.4
  rails:
    build:
      context: .
    environment:
      - GOOGLE_MAPS_DISTANCE_MATRIX_API_KEY
    volumes:
      - .:/home/riderank/riderank
    ports:
      - 3000:3000
